### ISSUE TITLE
Android Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by ruchitshah21** [dev-juyoung/CroPicker#2]
Attribute application@name value=(com.xyz.BaseApplication) from AndroidManifest.xml:59:9-40
	is also present at [xyz.dev_juyoung:cropicker:1.0.2] AndroidManifest.xml:12:9-75 value=(xyz.dev_juyoung.cropicker.base.CroPickerApplication).
	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:58:5-339:19 to override.

**Comment by dev-juyoung** [comment]
I will comment on that issue in issues #3
